spring:
  application:
    name: my-consul-client
  profiles:
    active: dev
  cloud:
    consul:
      host: 192.168.56.101
      port: 8500
      discovery:
        heartbeat:
          enabled: true # 心跳机制
          ttl: 10s # 项目向consul发送心跳的间隔
        enabled: true # 是否拉取服务
        register: true # 是否注册服务
        instance-id: custom-service-id # 自定义instance-id
        service-name: ${spring.application.name} # 自定义service-name
        metadata: # 元数据
          my-field: myValue
          another-field: anotherValue
      config: # consul分布式配置
        enabled: true # 是否开启
        prefixes: # 前缀
          - configuration
        default-context: apps # 上下文，默认为项目名，application可以被所有项目使用
        profile-separator: ':' # profile分隔符，和prefixes,default-context一起组成配置路径
        format: key_value # 配置格式
        watch:
          delay: 1500 # 自动刷新的间隔时间
        fail-fast: false # 配置功能不可用时是否报错，false可以使项目忽略错误正常启动
    openfeign: # openfeign配置
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
      circuitbreaker: # openfeign中断路器配置
        enabled: true
        alphanumeric-ids:
          enabled: true
        group:
          enabled: true
    loadbalancer: # loadbalancer配置
      enabled: true
  config: # 分布式配置地址，默认和consul配置的地址一样
    import: 'optional:consul:'
resilience4j: # resilience4j配置
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 100 # 滑动窗口
        sliding-window-type: count_based # 滑动窗口计算方式
        wait-duration-in-open-state: 5000 # 断路器由打开变为半开的等待时间
        permitted-number-of-calls-in-half-open-state: 20 # 断路器半开状态下允许的请求数量
        failure-rate-threshold: 50 # 阈值，断路器关闭时失败比例大于等于50%断路器会打开，断路器半开时失败比例小于50%断路器会关闭
  timelimiter:
    configs:
      default:
        timeout-duration: 5s # 超时时间
        cancel-running-future: false # 如果此时正在进行异步调用，是否要取消
  ratelimiter:
    configs:
      default:
        limit-for-period: 10 # 在一次刷新周期内，允许执行的最大请求数
        limit-refresh-period: 500ms # 限流器每隔limitRefreshPeriod刷新一次，将允许处理的最大请求数量重置为limitForPeriod
        timeout-duration: 3s # 线程等待权限的默认等待时间



server:
  port: 8080

management:
  server:
    port: 4452
